[package]
name = "nohuman"
description = "Remove human reads from a sequencing run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.0"
anyhow = "1.0.75"
flate2 = "1.0.28"
reqwest = { version = "0.11.22", features = ["blocking", "stream"] }
tar = "0.4.40"
thiserror = "1.0.50"
tempfile = "3.8.1"
toml = "0.8.8"
serde = { version = "1.0.193", features = ["derive"] }
md5 = "0.7.0"
lazy_static = "1.4.0"
dirs = "5.0.1"
futures-util = "0.3.29"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
